#!/usr/bin/env bash

container_base_distro=ubuntu:25.04
target=yocto-buildenv

on_exit () {
  if [ -n "$ctr" ]; then
    buildah rm "$ctr"
  fi
}

die () {
  echo "$@" >&2
  exit 1
}

buildah_run () {
  buildah run --network host "$ctr" "$@"
}

print_usage () {
  cat << EOF
Usage: build-devenv-container OPTIONS...

Build the $target container, intended for application development
(build, tests, code coverage etc.) and yocto builds.

Options:
  --help
  -j N, --jobs=N
    Allow N jobs at once (default: $default_jobs)
EOF
}

parse_args () {
  declare parsed

  # Parse options with getopt
  if ! parsed=$(getopt -o j: --long help,jobs: -n "$0" -- "$@"); then
    print_usage
    exit 1
  else
    eval set -- "$parsed"
  fi

  # Extract options and their arguments
  while true; do
    case "$1" in
      --help)
        print_usage
        exit 0
        ;;
      --jobs|-j)
        jobs="$2"
        shift
        ;;
      --)
        shift
        break
        ;;
      *)
        die "Invalid option: $1"
        print_usage
        exit 1
        ;;
    esac
  done
}

main () {
  set -eu -o pipefail
  trap on_exit EXIT

  this_script=$(readlink -fv "$0")
  this_dir=$(dirname "$this_script")

  ctr=""

  declare jobs
  declare default_jobs=8

  default_jobs=$(nproc)
  : ${default_jobs:=8}

  jobs="${default_jobs}"

  parse_args "$@"

  ctr=$(buildah from --name "$target" "$container_base_distro")
  if [ -z "$ctr" ]; then
    die "Container creation failed."
  fi

  packages=(
	  build-essential chrpath cpio debianutils diffstat file gawk gcc git iputils-ping libacl1
	  liblz4-tool locales python3 python3-git python3-jinja2 python3-pexpect python3-pip
	  python3-subunit socat texinfo unzip wget xz-utils zstd build-essential chrpath cpio
	  debianutils diffstat file gawk gcc git iputils-ping libacl1 liblz4-tool locales python3
	  python3-git python3-jinja2 python3-pexpect python3-pip python3-subunit socat texinfo
	  unzip wget xz-utils zstd vim tig tmux openssh-client
  )

  apt_env=(DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC)
  if [ -v APT_HTTP_PROXY ]; then
    apt_env+=(http_proxy="${APT_HTTP_PROXY}")
  fi

  # XXX: Disable security.ubuntu.com to work around proxy issue.

  buildah_run sed -i -e 's/^\([^#].*security.ubuntu.com\)/# \1/' /etc/apt/sources.list
  buildah_run sh -c "echo deb http://fr.archive.ubuntu.com/ubuntu/ focal-security main restricted universe >> /etc/apt/sources.list"

  buildah_run env "${apt_env[@]}" apt-get update
  buildah_run env "${apt_env[@]}" apt-get dist-upgrade --no-install-recommends -y
  buildah_run env "${apt_env[@]}" apt-get install -y locales tzdata

  buildah_run localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

  buildah config --env LANG=en_US.UTF-8 "$ctr"

  buildah_run env "${apt_env[@]}" apt-get install --no-install-recommends -y "${packages[@]}"
  buildah_run apt-get clean

  # Clean-up
  buildah_run sh -c "rm -rf /var/lib/apt/lists/*"
  # TODO: /tmp/* /var/tmp/* /root/.cache"

  groupname=yocto
  username=yocto

  buildah_run groupadd -g 30000 $groupname
  buildah_run useradd -u 30000 -g 30000 -m -s /bin/bash $username

  home=/home/$username

  # sudo for normal user accounts.
  # Give sudo rights to everyone (safe in a rootless container).
  buildah add --chmod 0400 "$ctr" "$this_dir/sudoers-all" /etc/sudoers.d/all
  buildah add --chmod 0400 "$ctr" "$this_dir/sudoers-preserve-proxy" /etc/sudoers.d/preserve-proxy

  unset http_proxy https_proxy HTTP_PROXY HTTPS_PROXY
  buildah_run python3 -m pip install --break-system-packages "kas==5.1"

  buildah config \
    --user $username \
    --workingdir "$home" \
    --env USER=$username \
    --cmd /bin/bash \
    "$ctr"

  buildah commit "$ctr" "$target"
}

main "$@"
